# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MorrAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MaterialComponents'
  # Pods for MorrAssignment
  

  target 'MorrAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MorrAssignmentUITests' do
    # Pods for testing
  end

end
